version: "3.9"
services:
  postgres:
    container_name: marlerino_db
    image: postgres
    restart: unless-stopped
    volumes:
      - "postgresql-14:/var/lib/postgresql/data:rw"
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}

    ports:
      - "${PG_PORT}:5432"


volumes:
  postgresql-14:
