version: "3.9"
services:
  postgres:
    container_name: marlerino_db
    image: postgres
    restart: unless-stopped
    volumes:
      - "postgresql-14:/var/lib/postgresql/data:rw"
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}

    ports:
      - "${PG_PORT}:5432"


  api:
    restart: always
    environment:
      APP_NAME: ${APP_NAME}
      HOST: ${HOST}
      PORT: ${PORT}
      PG_HOST: ${PG_HOST}
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_PORT: ${PG_PORT}
      PG_DATABASE: ${PG_DATABASE}
      KEITARO_DOMAIN: ${KEITARO_DOMAIN}
      KEITARO_API_KEY: ${KEITARO_API_KEY}
      KEITARO_API_DOMAIN: ${KEITARO_API_DOMAIN}

    network_mode: host
    build:
      context: .
      dockerfile: ./src/Dockerfile
    depends_on:
      - postgres
    ports:
      - "${PORT}:8000"


volumes:
  postgresql-14:
